config/routes.rb
Recipe::Application.routes.draw do

  resources :food_recipes, :except => :destroy
  root :to => 'food_recipes#index'
end

app/models/food_recipe.rb
class FoodRecipe < ActiveRecord::Base

  #require 'xml'

  fields = 'food_recipes.*, lm_by.name as last_made_by_name, a_by.name as added_by_name'
  joins = 'left outer join users lm_by on lm_by.id=last_made_by_id left outer join users a_by on a_by.id=added_by_id'
  serialize :ingredients, Array
  serialize :steps, Array
  
  attr_accessible :name, :ingredients, :steps
  
  belongs_to :added_by, :class_name => 'User'
  belongs_to :last_made_by, :class_name => 'User'
  
  scope :recently_made,  :select => fields, :joins => joins, :limit => 5, :order => 'last_made desc'
  scope :recently_added, :select => fields, :joins => joins, :limit => 3, :order => 'food_recipes.created_at desc'
  
  def self.search(term)
    select('food_recipes.*, lm_by.name as last_made_by_name, a_by.name as added_by_name' + ", match(food_recipes.name,description,tag_line,recipe_from,ingredients,steps) against ('"+term+"') as score")
      .where("match(food_recipes.name,description,tag_line,recipe_from,ingredients,steps) against ('"+term+"')")
      .order('score desc')
      .joins('left outer join users lm_by on lm_by.id=last_made_by_id left outer join users a_by on a_by.id=added_by_id')
      .limit(10)
  end
  
  #def self.loadFromFile(filename)
  #  doc = XML::Document.file(filename)
  #  
  #  doc.root.each_element do |e| 
  #    r = FoodRecipe.find_or_create_by_name(e.find("Title").first.content)
  #    r.recipe_from = e.find("FromName").first.content
  #    r.servings = e.find("Serves").first.content
  #    r.ingredients = convertToArray(e.find("Ingredients").first.content)
  #    r.steps = convertToArray(e.find("Directions").first.content)
  #    r.save
  #  end
  #  
  #end
  
  def self.convertToArray(string_value)
    string_value.lines.map {|x| x.strip }.reject { |x| x.blank? }
  end
  
  def steps= (value)
    value = FoodRecipe.convertToArray(value) if !value.is_a? Array
    write_attribute(:steps, value)
  end
  
  def ingredients= (value)
    value = FoodRecipe.convertToArray(value) if !value.is_a? Array
    write_attribute(:ingredients, value)
  end
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  attr_accessible :name, :step_order
end

app/models/step.rb
class Step < ActiveRecord::Base
  attr_accessible :name, :step_order
end

app/models/user.rb
class User < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/food_recipes_controller.rb
class FoodRecipesController < ApplicationController
  # GET /food_recipes
  # GET /food_recipes.json
  def index
    @food_recipes = FoodRecipe.recently_made
    
    if params[:search]
      @food_recipes = FoodRecipe.search(params[:search])
      @food_recipes = @food_recipes.offset(params[:page].to_i * 10) if params[:page]
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @food_recipes }
    end
  end

  # GET /food_recipes/1
  # GET /food_recipes/1.json
  def show
    @food_recipe = FoodRecipe.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @food_recipe }
    end
  end

  # GET /food_recipes/new
  # GET /food_recipes/new.json
  def new
    @food_recipe = FoodRecipe.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @food_recipe }
    end
  end

  # GET /food_recipes/1/edit
  def edit
    @food_recipe = FoodRecipe.find(params[:id])
  end

  # POST /food_recipes
  # POST /food_recipes.json
  def create
    @food_recipe = FoodRecipe.new(params[:food_recipe])

    respond_to do |format|
      if @food_recipe.save
        format.html { redirect_to @food_recipe, notice: 'Food recipe was successfully created.' }
        format.json { render json: @food_recipe, status: :created, location: @food_recipe }
      else
        format.html { render action: "new" }
        format.json { render json: @food_recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /food_recipes/1
  # PUT /food_recipes/1.json
  def update
    @food_recipe = FoodRecipe.find(params[:id])

    respond_to do |format|
      if @food_recipe.update_attributes(params[:food_recipe])
        format.html { redirect_to @food_recipe, notice: 'Food recipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @food_recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_recipes/1
  # DELETE /food_recipes/1.json
  def destroy
    @food_recipe = FoodRecipe.find(params[:id])
    @food_recipe.destroy

    respond_to do |format|
      format.html { redirect_to food_recipes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_recipes_helper.rb
module FoodRecipesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/food_recipes/_form.html.erb
<%= form_for(@food_recipe) do |f| %>
  <% if @food_recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food_recipe.errors.count, "error") %> prohibited this food_recipe from being saved:</h2>

      <ul>
      <% @food_recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/food_recipes/edit.html.erb
<h1>Editing food_recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @food_recipe %> |
<%= link_to 'Back', food_recipes_path %>

app/views/food_recipes/index.html.erb
<div class="container">
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Elisa's  Kitchen</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="homeTab active"><a href="#">Home</a></li>
          <li class="newRecipeTab"><a href="#recipe/new">New</a></li>
          <li class="searchTab"><a href="#search">Search</a></li>
          <li class="editTab" style="display:none"><a href="#edit">Edit</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        </ul>
        <form class="navbar-form navbar-right" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
        </form>
      </div>
    </div>
  </nav>
</div>

<div class="container" id="main">
  
</div>

<script type="text/javascript">
  $(function() {
    // Blog is the app name
    window.Recipe.recently_made = <%= FoodRecipe.recently_made.to_json.html_safe %>
    window.Recipe.recently_added = <%= FoodRecipe.recently_added.to_json.html_safe %>
    //window.router = new Recipe.Routers.FoodRecipesRouter({recently_made:  -%>,recently_added: <%= FoodRecipe.recently_added.to_json.html_safe -%>});
    //Backbone.history.start();
  });
</script>

app/views/food_recipes/new.html.erb
<h1>New food_recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', food_recipes_path %>

app/views/food_recipes/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_food_recipe_path(@food_recipe) %> |
<%= link_to 'Back', food_recipes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Recipe</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
   
</body>
</html>